name: Upload Zip to S3

on:
  push:
    branches:
      - main 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up AWS CLI
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1 # Change this to your desired AWS region
    
    - name: Requirements install
      run: ./install.sh 

    - name: Create a ZIP file
      run: ./pack.sh

    - name: Update Lambda function code
      run: |
          aws lambda update-function-code \
            --function-name fast-api \
            --zip-file ./function.zip  
            --publish \
            --region ap-south-1  
